### ISSUE TITLE
How can we align link and pointer (->) to the specific row?

### ISSUE THREAD

**Issue by uds214125** [NorthwoodsSoftware/gojs-angular-basic#12]
The anchor should start from the PrimaryKey row and end at the ForeignKey row.

Like the below picture

![image](https://user-images.githubusercontent.com/17702550/97417029-36e2fb80-192d-11eb-919b-f75e351a0b2b.png)

**Comment by simonsarris** [comment]
For GoJS related issues, please use the [forum](https://forum.nwoods.com/) or [contact us](https://www.nwoods.com/contact.html).
