### ISSUE TITLE
unable to reproduce gojs-angular-basic sample

### ISSUE THREAD

**Issue by johnasherrayan** [NorthwoodsSoftware/gojs-angular-basic#2]
![gojsangular](https://user-images.githubusercontent.com/42939491/74608100-8c001980-50de-11ea-976b-3a07a3fb3bba.PNG)

"gojs": "^2.1.0-beta1", 
"gojs-angular": "^1.0.1", 
"@angular/common": "~8.2.9", 
"@angular/compiler": "~8.2.9", 
"@angular/core": "~8.2.9",

**Comment by rjohnson465** [comment]
Hello, thanks for reporting this! I'll push an updated package.json file to this repo tomorrow, but for now, just make sure your gojs dependency is:

"gojs": "^2.1.0"

and for gojs-angular:

"gojs-angular": "^1.0.1"

**Comment by rjohnson465** [comment]
This issue should now be resolved; feel free to reach out again if you encounter more problems

**Comment by alanpurple** [comment]
still same with angular 16
