### ISSUE TITLE
`npm install` giving ''Unexpected end of JSON input''

### ISSUE THREAD

**Issue by Tulsani** [NorthwoodsSoftware/gojs-angular-basic#4]
I was trying to use the boilerplate to get better understanding of go-js in Angular
Post cloning the repo when I run 'npm install' for the repo to install its dependencies it produces the error 
I am using Angular 9+ on my windows 10.
How can I resolve it? 
Thanks a lot !!

**Comment by rjohnson465** [comment]
Sorry about that! Thanks for letting me know, I have fixed this. Just get the latest version and you should be all set!

Let me know if you run into any other bugs or problems
