### ISSUE TITLE
Does it support Angular17？

### ISSUE THREAD

**Issue by iamk123** [NorthwoodsSoftware/gojs-angular-basic#54]

**Comment by WalterNorthwoods** [comment]
I have updated this sample to Angular 18.  It continues to use gojs-angular 2.0.7.

If you want to use GoJS v3, there's a bug in the Babel transpiler/minimizer.  You will need to use at least v3.0.5, unless you use an **Overview**, in which case you'll need at least v3.0.6, which include work-arounds for that Babel bug.
